apiVersion: v1
kind: Service
metadata:
  labels:
    app: amortization-service
  name: amortization-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32622
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: amortization-service
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amortization-service
  labels:
    app: amortization-service
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: amortization-service
  template:
    metadata:
      labels:
        app: amortization-service
    spec:
      containers:
        - name: accounts
          image: gcr.io/xylia-platform/amortization-service:1.0.0

          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5

          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5

          resources:
            requests:
              memory: "800M"
              cpu: "100m"
            limits:
              memory: "900M"
              cpu: "250m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
